apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-services-name
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: your-services-name
  template:
    metadata:
      labels:
        app: your-services-name
    spec:
      containers:
        - name: your-services-name
          image: us-central1-docker.pkg.dev/durable-trainer-372420/red-sentry/your-services-name-stg:latest
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: connections-config
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: connections-config
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                configMapKeyRef:
                  name: connections-config
                  key: DB_PASS
            - name: DB_SCHEMA
              valueFrom:
                configMapKeyRef:
                  name: connections-config
                  key: DB_SCHEMA
            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: connections-config
                  key: FRONTEND_URL
            - name: RMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: connections-config
                  key: RMQ_HOST
            - name: RMQ_USER
              valueFrom:
                configMapKeyRef:
                  name: connections-config
                  key: RMQ_USER
            - name: RMQ_PASS
              valueFrom:
                configMapKeyRef:
                  name: connections-config
                  key: RMQ_PASS
          livenessProbe:
            initialDelaySeconds: 120
            periodSeconds: 180
            timeoutSeconds: 180
            failureThreshold: 3
            httpGet:
              scheme: HTTP
              path: /health
              port: 80
